# Generated by Django 5.2 on 2025-04-28 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_service'),
        ('social_django', '0016_alter_usersocialauth_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('social_django.association',),
        ),
        migrations.CreateModel(
            name='NonceProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Нонс',
                'verbose_name_plural': 'Нонсы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('social_django.nonce',),
        ),
        migrations.CreateModel(
            name='UserSocialAuthProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Связанный аккаунт пользователя',
                'verbose_name_plural': 'Связанные аккаунты пользователей',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('social_django.usersocialauth',),
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.CreateModel(
            name='ServiceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=100, verbose_name='Вид услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.service', verbose_name='Услуга')),
            ],
        ),
    ]
