# Generated by Django 5.2 on 2025-04-29 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_associationproxy_nonceproxy_usersocialauthproxy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('confirmed', 'Подтверждён'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='pending', max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.userprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.service')),
            ],
        ),
        migrations.DeleteModel(
            name='AssociationProxy',
        ),
        migrations.DeleteModel(
            name='NonceProxy',
        ),
        migrations.DeleteModel(
            name='UserSocialAuthProxy',
        ),
    ]
